import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import navItems from "@/data/data";
import { FloatingNav } from "@/components/ui/floating-navbar";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/pages/Footer";
import Social from "@/components/pages/Social";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Sakshi's Portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<FloatingNav navItems={navItems} />
				<ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
					{children}
				</ThemeProvider>
				<Social />
				<Toaster />
				<Footer />
			</body>
		</html>
	);
}
